### ISSUE TITLE
RestfulZoldNet.java:38-39: Add methods for API entry...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/zold-java-client#11]
The puzzle `4-040a72fe` from #4 has to be resolved: 

https://github.com/amihaiemil/zold-java-client/blob/795d20c9c15a6f6bcf372feaafb569f5c0eb26b4/src/main/java/com/amihaiemil/zold/RestfulZoldNet.java#L38-L39

The puzzle was created by @amihaiemil on 15-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by amihaiemil** [comment]
We should follow the example of [zold-ruby-sdk](https://github.com/zold-io/zold-ruby-sdk) -- start with a method from there :)

**Comment by 0crat** [comment]
Job [#11](https://github.com/amihaiemil/zold-java-client/issues/11) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#11](https://github.com/amihaiemil/zold-java-client/issues/11) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/1587118d-79f1-44cf-aa2e-81af878fdcfb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@amihaiemil 
One of the methods I was adding is 
`void pay(String keygap, String user, double amount, String details);`
But it has more than 3 parameters
I get that error

> [ERROR] More than 3 parameters (found 4). [ParameterNumber]

what should I do? I was thinking of creating a class called payment that holds the recipient, amount and details

**Comment by ammaratef45** [comment]
@0crat wait
waiting for a decision

**Comment by 0crat** [comment]
> @0crat wait waiting for a decision ([here](https://github.com/amihaiemil/zold-java-client/issues/11#issuecomment-455840647))

@ammaratef45 The impediment for [#11](https://github.com/amihaiemil/zold-java-client/issues/11) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by amihaiemil** [comment]
@ammaratef45 regarding number of parameters, I would simply escape the Checkstyle rule. However, method pay(...) should be on the Wallet interface. See #16. 

Make a PR in which you introduce that interface, with the method :)
Escape checkstyle using the ``@checkstyle`` annotation.

**Comment by ammaratef45** [comment]
@amihaiemil yes I'm already making it in the interface

**Comment by 0pdd** [comment]
The puzzle `4-040a72fe` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#11](https://github.com/amihaiemil/zold-java-client/issues/11) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
