### ISSUE TITLE
Add util classes

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/zold-java-client#15]
Util classes such as MatchStatus, JavaResource and unit test infrastructure should be added, same as in docker-java-api.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#15](https://github.com/amihaiemil/zold-java-client/issues/15) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/e98e7e84-4645-4d0a-91b5-6ee0b4b4f1a0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/amihaiemil/zold-java-client/issues/15#issuecomment-455955576))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#15](https://github.com/amihaiemil/zold-java-client/issues/15), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#15` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#15](https://github.com/amihaiemil/zold-java-client/issues/15) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/e5929a15-1d97-425b-a5f5-735756cb7930); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job
