### ISSUE TITLE
ZoltWts.pull() :: Wallet

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/zold-java-client#16]
Following the [ruby-sdk](https://github.com/zold-io/zold-ruby-sdk/blob/master/lib/zold/wts.rb), the first method we need is ``pull()`` which will return the ``Wallet`` with all its operations (``balance()``, ``id()`` etc). ``Wallet`` should, of course, be a ``JsonObject`` as well.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#16](https://github.com/amihaiemil/zold-java-client/issues/16) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/fe543096-2de3-4bb2-9b67-23867bf536a5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#16](https://github.com/amihaiemil/zold-java-client/issues/16) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
