### ISSUE TITLE
RestfulZoldWts.java:38: implement body of interface methods.

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/zold-java-client#19]
The puzzle `11-721420d3` from #11 has to be resolved: 

https://github.com/amihaiemil/zold-java-client/blob/10d890e0222194acdbc0b3c1bfa68f14c727b5a3/src/main/java/com/amihaiemil/zold/RestfulZoldWts.java#L38-L38

The puzzle was created by @amihaiemil on 20-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#19](https://github.com/amihaiemil/zold-java-client/issues/19) is now in scope, role is `DEV`

**Comment by amihaiemil** [comment]
@ammaratef45 @OleksandrSankin Thanks again for your help! I will implement this tomorrow so you have an example of what I have in mind :)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by ammaratef45** [comment]
@amihaiemil Great, that would be nice 😄

**Comment by 0pdd** [comment]
The puzzle `11-721420d3` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#19](https://github.com/amihaiemil/zold-java-client/issues/19) is now out of scope
