### ISSUE TITLE
PayloadOf.java:42: Add tests for PayloadOf.

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/zold-java-client#25]
The puzzle `25-8ad4a268` from #25 has to be resolved: 

https://github.com/amihaiemil/zold-java-client/blob/ffe8aae48a9e6523d002e9646c7a97c666005cd1/src/main/java/com/amihaiemil/zold/PayloadOf.java#L42-L42

The puzzle was created by @amihaiemil on 21-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
Job [#25](https://github.com/amihaiemil/zold-java-client/issues/25) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/amihaiemil/zold-java-client/issues/25#issuecomment-458214007))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#25](https://github.com/amihaiemil/zold-java-client/issues/25), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#25](https://github.com/amihaiemil/zold-java-client/issues/25) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/55b631b7-ecf4-46e9-9dd5-387026ab5068); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/amihaiemil/zold-java-client/issues/25#issuecomment-459403332))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#25](https://github.com/amihaiemil/zold-java-client/issues/25), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#25](https://github.com/amihaiemil/zold-java-client/issues/25) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/13bbfda9-83ef-433f-8653-40b49130f944); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#25](https://github.com/amihaiemil/zold-java-client/issues/25) assigned to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/e378548d-ba60-4a27-88a2-e2891d06e749); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by denis-konovalyenko** [comment]
@ammaratef45 , as you are now an architect, could you please close this issue as 0pdd has not done this for some reasons? The puzzle was removed in the scope of the merged pull request.

**Comment by ammaratef45** [comment]
@denis-konovalyenko I can only order rultor to merge,
@amihaiemil please have a look

**Comment by 0crat** [comment]
The job [#25](https://github.com/amihaiemil/zold-java-client/issues/25) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)
