### ISSUE TITLE
Adapt testing framework

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/zold-java-client#26]
Addapt class ``AsserRequest`` to support multiple (consecutive) HttpRequests. Each request should be asserted against its conditions and have its own response.

**Comment by 0crat** [comment]
Job [#26](https://github.com/amihaiemil/zold-java-client/issues/26) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#26](https://github.com/amihaiemil/zold-java-client/issues/26) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/c968ecab-cb2c-41ee-8bca-b7e6746c409e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#26` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Job was finished in 19 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#26](https://github.com/amihaiemil/zold-java-client/issues/26) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)
