### ISSUE TITLE
Release 0.0.1

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/zold-java-client#28]
The very first version: it will just pull a wallet and check for its id. It also has a few bugs, most likely.

**Comment by amihaiemil** [comment]
@rultor release it, tag is `0.0.1`

**Comment by amihaiemil** [comment]
@yegor256 @g4s8 version `0.0.1` is on Maven Central. It's very primitive and it has no tests yet, but please try it out. So far, you can pull the wallet and read its id:

```java
final ZoldWts wts = new RestfulZoldWts("...api key...");
final Wallet wallet = wts.pull();
System.out.println("Wallet Id: " + wallet.getId());
```

``wts.pull()`` will take about 1 minute to complete, since it also waits for the network job to be finished.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#28` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by g4s8** [comment]
@amihaiemil thanks
