### ISSUE TITLE
RtWallet.java:40-41: Continue implementing Wallet...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/zold-java-client#29]
The puzzle `19-e3637f82` from #19 has to be resolved: 

https://github.com/amihaiemil/zold-java-client/blob/721134ab57f7273156efa9e83fa8d1c668a23b2c/src/main/java/com/amihaiemil/zold/RtWallet.java#L40-L41

The puzzle was created by @amihaiemil on 21-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#29](https://github.com/amihaiemil/zold-java-client/issues/29) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#29](https://github.com/amihaiemil/zold-java-client/issues/29) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/aff2d0c1-3aca-4b8a-9eb9-a8f1ec0a4387); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `19-e3637f82` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#29](https://github.com/amihaiemil/zold-java-client/issues/29) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
