### ISSUE TITLE
RtWallet.java:42: Write unit test for all wallet operations.

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/zold-java-client#34]
The puzzle `29-6cca827c` from #29 has to be resolved: 

https://github.com/amihaiemil/zold-java-client/blob/733ba86b0cc0ca695cc7d952b69a6585db7460bb/src/main/java/com/amihaiemil/zold/RtWallet.java#L42-L42

The puzzle was created by @ammaratef45 on 24-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#34](https://github.com/amihaiemil/zold-java-client/issues/34) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#34](https://github.com/amihaiemil/zold-java-client/issues/34) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/1cd8f6fe-9bfa-414a-be09-135a3fc22ea4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/amihaiemil/zold-java-client/issues/34#issuecomment-457930879))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#34](https://github.com/amihaiemil/zold-java-client/issues/34), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#34](https://github.com/amihaiemil/zold-java-client/issues/34) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/734021ec-cbb9-4ff3-b6c7-15263a475c83); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#34` already assigned to @ammaratef45, can't assign to @ammaratef45

**Comment by ammaratef45** [comment]
@amihaiemil 
Sorry if my question is naive, should we add since tag for new files as 0.0.2 instead of 0.0.1?

**Comment by ammaratef45** [comment]
@amihaiemil we will need to mock a wallet to be used for this test?

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/amihaiemil/zold-java-client/issues/34#issuecomment-459402688))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#34](https://github.com/amihaiemil/zold-java-client/issues/34), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/amihaiemil/zold-java-client/issues/34#issuecomment-462861866))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#34](https://github.com/amihaiemil/zold-java-client/issues/34), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#34](https://github.com/amihaiemil/zold-java-client/issues/34) assigned to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/bde1e01d-9891-47f5-8fc2-1e6be1969887); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `29-6cca827c` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#34](https://github.com/amihaiemil/zold-java-client/issues/34) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)
