### ISSUE TITLE
Incorrect interruption handling

### ISSUE THREAD

**Issue by g4s8** [amihaiemil/zold-java-client#39]
There is a `catch` block in `WaitForWallet`: https://github.com/amihaiemil/zold-java-client/blob/721134ab57f7273156efa9e83fa8d1c668a23b2c/src/main/java/com/amihaiemil/zold/WaitForWallet.java#L103-L107

it handles `InterruptedException` but doesn't set interrupted flag of the thread and doesn't terminate the job. It's not correct usage of this kind of exception. It should either add `InterruptedException` to method signature and do not handle it; or set interrupted flag and cancel running operation. 
see https://stackoverflow.com/q/3976344/1723695

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#39](https://github.com/amihaiemil/zold-java-client/issues/39) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/f61ca81c-28fc-45f7-ba78-cd17b689fa59); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@amihaiemil So, which option I implement: 
1) add `InterruptedException` to method signature and do not handle it; **OR**
2) set interrupted flag and cancel running operation?

**Comment by paulodamaso** [comment]
@0crat wait for answer of question in comment https://github.com/amihaiemil/zold-java-client/issues/39#issuecomment-461429646

**Comment by 0crat** [comment]
> @0crat wait for answer of question in comment https://github.com/amihaiemil/zold-java-client/issu... ([here](https://github.com/amihaiemil/zold-java-client/issues/39#issuecomment-461429969))

@paulodamaso The impediment for [#39](https://github.com/amihaiemil/zold-java-client/issues/39) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by amihaiemil** [comment]
@paulodamaso I would go with option 2: set interrupted flag and cancel running operation?

**Comment by paulodamaso** [comment]
@g4s8 Merged, please close

**Comment by g4s8** [comment]
@paulodamaso thanks

**Comment by 0crat** [comment]
The job [#39](https://github.com/amihaiemil/zold-java-client/issues/39) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
