### ISSUE TITLE
ZoldNet entry point

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/zold-java-client#4]
ZoldNet will be the entry point. RtZoldNet (RESTful ZoldNet) will be its public implementation.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) I'm not managing this repo, remove the [webhook](https://github.com/amihaiemil/zold-java-client/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `amihaiemil/zold-java-client` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `amihaiemil/zold-java-client` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by amihaiemil** [comment]
@ammaratef45 so would you like to help with this library? Shouldn't be complicated, we have [docker-java-api](http://github.com/amihaiemil/docker-java-api) as model (it will be almost 1:1 as architecture)

**Comment by ammaratef45** [comment]
@amihaiemil
Yes I would like to help,
You can rely on me I wish

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#4` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
