### ISSUE TITLE
RtWallet.java:45: implement the find method as in zold...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/zold-java-client#41]
The puzzle `33-e07698b5` from #33 has to be resolved: 

https://github.com/amihaiemil/zold-java-client/blob/1d7c29b68853662c8162d26a8459fffa61c4955a/src/main/java/com/amihaiemil/zold/RtWallet.java#L45-L45

The puzzle was created by @rultor on 05-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#41](https://github.com/amihaiemil/zold-java-client/issues/41) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#41](https://github.com/amihaiemil/zold-java-client/issues/41) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/96ae4394-cdfc-4ab8-b9cd-7c999f601487); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat wait for #43

**Comment by 0crat** [comment]
> @0crat wait for #43  ([here](https://github.com/amihaiemil/zold-java-client/issues/41#issuecomment-467310160))

@ammaratef45 The impediment for [#41](https://github.com/amihaiemil/zold-java-client/issues/41) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `33-e07698b5` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#41](https://github.com/amihaiemil/zold-java-client/issues/41) is now out of scope
