### ISSUE TITLE
Use BigDecimal instead of double

### ISSUE THREAD

**Issue by denis-konovalyenko** [amihaiemil/zold-java-client#44]
There are 2 methods of the `Wallet` interface, which uses `double` type: `balance` and `pay`.

>Representing money as a double or float will probably look good at first as the software rounds off the tiny errors, but as you perform more additions, subtractions, multiplications and divisions on inexact numbers, errors will compound and you'll end up with values that are visibly not accurate. This makes floats and doubles inadequate for dealing with money, where perfect accuracy for multiples of base 10 powers is required.

>A solution that works in just about any language is to use integers instead, and count cents. For instance, 1025 would be $10.25. Several languages also have built-in types to deal with money. Among others, Java has the BigDecimal class, and C# has the decimal type.

For more details please refer to [this resource](https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by denis-konovalyenko** [comment]
@amihaiemil , as an alternative, I am tending to like this more and more, we can easily go with `String` types for `balance` and `pay` methods and leave all type conversion/parsing for the upper/user layer:
```
    String balance();
    void pay(
        final String keygap, final String user,
        final String amount, final String details
    );
```
What do you think?

**Comment by amihaiemil** [comment]
@denis-konovalyenko looks good! We do it with Strings and let folks take care of it, it's safer :)

**Comment by 0crat** [comment]
Job [#44](https://github.com/amihaiemil/zold-java-client/issues/44) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)

**Comment by 0crat** [comment]
The job [#44](https://github.com/amihaiemil/zold-java-client/issues/44) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/000f08ed-5400-4822-9fb0-a0d90821193a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@denis-konovalyenko Is it fine now?

**Comment by denis-konovalyenko** [comment]
@ammaratef45 , what do you mean? As far as the pull request has been merged, 0crat should put the issue out of scope and close it. Maybe, it is too lazy today and it will take a bit of time to accomplish that. :)

**Comment by ammaratef45** [comment]
@denis-konovalyenko Hmmm, usually zerocrat doesn't close issues (reporter close it or PDD if it was a puzzle)
Am I missing something?

**Comment by denis-konovalyenko** [comment]
@amihaiemil , ah, no problem. I think this is not clearly stated in the policy (or I missed that).

**Comment by 0crat** [comment]
Job was finished in 31 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#44](https://github.com/amihaiemil/zold-java-client/issues/44) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
