### ISSUE TITLE
Android support is missed

### ISSUE THREAD

**Issue by wholegroup** [amihaiemil/zold-java-client#47]
This library can't be compile on Android while it uses Apache HttpClient.
Android in self contains very old version of Apache HttpClient (probably 3.x) and disallows using third-party classes of org.apache.http.* package. More over Google is going to remove Apache HttpClient at all and offers to use `java.net.HttpURLConnection` instead.

Currently zold-java-client uses org.apache.http.impl.client.HttpClients builder. 
This class is delivered [since 4.3](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClients.html). Android doesn't have this builder (see [here](https://android.googlesource.com/platform/external/apache-http/+/d42abb2/src/org/apache/http/impl/client))

Also pls look at https://github.com/ammaratef45/zold-android-wallet/issues/1

p.s. It's better do not use ```org.apache.http.*``` on Android at all as I understand
p.p.s. Apache HttpComponents 5.x has been moved to ```org.apache.hc.client5.*``` package.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@wholegroup[/z](https://www.0crat.com/u/wholegroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/GFCHY7NQG) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by wholegroup** [comment]
@amihaiemil I haven't tested, so I can't 100% be sure. There is no official information about android support, only a clue from [this ticket](https://issues.apache.org/jira/browse/HTTPCLIENT-1632)

**Comment by amihaiemil** [comment]
@wholegroup I see. Let's try switching to Apache 5.0

**Comment by amihaiemil** [comment]
@wholegroup I might not be so active the next days. When this task is finished, please ping me so we can release the library :)

**Comment by 0crat** [comment]
Job [#47](https://github.com/amihaiemil/zold-java-client/issues/47) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @wholegroup[/z](https://www.0crat.com/u/wholegroup)

**Comment by 0crat** [comment]
The job [#47](https://github.com/amihaiemil/zold-java-client/issues/47) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/40db3f54-f92b-4abe-b9ff-17ccf8334af6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by wholegroup** [comment]
@amihaiemil @ammaratef45 
I've made PR #48 
I made few tests on Android and it looked working.

**Comment by ammaratef45** [comment]
@amihaiemil please assign it to @wholegroup so he can get the credit of his work :+1:

**Comment by amihaiemil** [comment]
@0crat assign @wholegroup

**Comment by 0crat** [comment]
> @0crat assign @wholegroup  ([here](https://github.com/amihaiemil/zold-java-client/issues/47#issuecomment-469651238))

@amihaiemil The job [#47](https://github.com/amihaiemil/zold-java-client/issues/47) assigned to @wholegroup[/z](https://www.0crat.com/u/wholegroup), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/b5a121a1-b59b-4210-a4da-a157c48eb230); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @wholegroup[/z](https://www.0crat.com/u/wholegroup) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by wholegroup** [comment]
@amihaiemil PR #48 has been merged. 
Let's close this issue.

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#47](https://github.com/amihaiemil/zold-java-client/issues/47) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @wholegroup[/z](https://www.0crat.com/u/wholegroup)
