### ISSUE TITLE
Release 0.0.2

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/zold-java-client#49]
Let's release 0.0.2

**Comment by amihaiemil** [comment]
@ammaratef45 @wholegroup I guess we can release it, since Apache is updated, right?

**Comment by ammaratef45** [comment]
Yes release and I will try using it in my app again 👍

**Comment by amihaiemil** [comment]
@rultor release it, tag is `0.0.2`

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#49` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
