### ISSUE TITLE
0crat test

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/zold-java-client#5]

**Comment by 0crat** [comment]
Job [#5](https://github.com/amihaiemil/zold-java-client/issues/5) is now in scope, role is `DEV`

**Comment by amihaiemil** [comment]
@0crat out

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/amihaiemil/zold-java-client/issues/5#issuecomment-454124756))

@amihaiemil Job `gh:amihaiemil/zold-java-client#5` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/amihaiemil/zold-java-client/issues/5#issuecomment-454124756))

@amihaiemil The job [#5](https://github.com/amihaiemil/zold-java-client/issues/5) is now out of scope

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#5` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
