### ISSUE TITLE
String.join is not supported in Android

### ISSUE THREAD

**Issue by ammaratef45** [amihaiemil/zold-java-client#50]
Upgrading to the Apache 5.x did solve the problem ammaratef45/zold-android-wallet#1
Unfortunately, The `UserAgentRequestHeader.java` is using the static method `join` from `String` class.

Android supports only a subset of 1.8 JDK and that method is not one of them.
We need to change it and use something else.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#50](https://github.com/amihaiemil/zold-java-client/issues/50) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by amihaiemil** [comment]
@ammaratef45 would you like to fix this? :D

**Comment by ammaratef45** [comment]
@amihaiemil Sure, let me do that.
At least I can test my solution before making a PR :laughing:

**Comment by amihaiemil** [comment]
@0crat assign @ammaratef45

**Comment by 0crat** [comment]
> @0crat assign @ammaratef45 ([here](https://github.com/amihaiemil/zold-java-client/issues/50#issuecomment-470026383))

@amihaiemil The job [#50](https://github.com/amihaiemil/zold-java-client/issues/50) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/85c7ee44-2d21-4e09-92a0-e5c2e92dc95a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by wholegroup** [comment]
@ammaratef45 It says https://developer.android.com/reference/java/lang/String.html#join(java.lang.CharSequence,%20java.lang.CharSequence...) String.join was added in API level 26
I've been tested this and it works with `targetSdkVersion 26`

What kind of errors did you get?

**Comment by ammaratef45** [comment]
@wholegroup Yes, but API 26 is quite a small range of devices to support.
I'm testing on a mobile that has API 23 (quite old).

**Comment by ammaratef45** [comment]
@wholegroup Look who also was added in API 26? https://developer.android.com/reference/java/time/Duration
:laughing:

**Comment by amihaiemil** [comment]
@rultor release it, tag is `0.0.3`

**Comment by amihaiemil** [comment]
@ammaratef45 version ``0.0.3`` containing this fix is released :) thanks!

**Comment by 0crat** [comment]
Job was finished in 47 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#50](https://github.com/amihaiemil/zold-java-client/issues/50) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
