### ISSUE TITLE
RtWallet.java:48: Write unit tests for uncovered wallet...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/zold-java-client#56]
The puzzle `34-5b6d6642` from #34 has to be resolved: 

https://github.com/amihaiemil/zold-java-client/blob/f6292d79a8908718d163d14c42a45bcf768a6602/src/main/java/com/amihaiemil/zold/RtWallet.java#L48-L48

The puzzle was created by Denis Konovalyenko on 23-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#56](https://github.com/amihaiemil/zold-java-client/issues/56) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#56](https://github.com/amihaiemil/zold-java-client/issues/56) assigned to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/905da27e-3f5b-4e60-91cf-7ca688882295); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by denis-konovalyenko** [comment]
@0crat wait for the pull request #57 merge.

**Comment by 0crat** [comment]
> @0crat wait for the pull request #57 merge. ([here](https://github.com/amihaiemil/zold-java-client/issues/56#issuecomment-478332006))

@denis-konovalyenko The impediment for [#56](https://github.com/amihaiemil/zold-java-client/issues/56) was registered successfully by @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)

**Comment by 0pdd** [comment]
The puzzle `34-5b6d6642` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#56](https://github.com/amihaiemil/zold-java-client/issues/56) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)
