### ISSUE TITLE
Improve the find method to search with id, date, amount and prefix parameters 

### ISSUE THREAD

**Issue by denis-konovalyenko** [amihaiemil/zold-java-client#58]
According to [wts code base](https://github.com/zold-io/wts.zold.io/blob/7e3507fe96cd8cc6a0bd32a22ac1ab17644cc3e1/wts.rb#L512), the find transactions operation can be invoked with more than 2 parameters, which are currently available (`bnf` and `details`):
- `id`
- `date`
- `amount`
- `prefix`

It would be nice to have this functionality completed.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#58](https://github.com/amihaiemil/zold-java-client/issues/58) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)

**Comment by 0crat** [comment]
The job [#58](https://github.com/amihaiemil/zold-java-client/issues/58) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/ae54baad-1069-4ee1-857d-b474e4970417); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat wait for merging #60

**Comment by 0crat** [comment]
> @0crat wait for merging #60  ([here](https://github.com/amihaiemil/zold-java-client/issues/58#issuecomment-477523814))

@ammaratef45 The impediment for [#58](https://github.com/amihaiemil/zold-java-client/issues/58) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@denis-konovalyenko Can you close this issue?

**Comment by denis-konovalyenko** [comment]
@ammaratef45 , thanks for the solution!

**Comment by 0crat** [comment]
The job [#58](https://github.com/amihaiemil/zold-java-client/issues/58) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
