### ISSUE TITLE
RtWallet.java:49: Write unit tests for uncovered wallet...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/zold-java-client#61]
The puzzle `56-5b6d6642` from #56 has to be resolved: 

https://github.com/amihaiemil/zold-java-client/blob/c0c915e69773a5d0c366cb6f466d067035c23988/src/main/java/com/amihaiemil/zold/RtWallet.java#L49-L49

The puzzle was created by Denis Konovalyenko on 26-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#61](https://github.com/amihaiemil/zold-java-client/issues/61) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job [#61](https://github.com/amihaiemil/zold-java-client/issues/61) is already in scope

**Comment by 0crat** [comment]
The job [#61](https://github.com/amihaiemil/zold-java-client/issues/61) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/786694c8-c791-4ec5-9398-455c2839a548); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/amihaiemil/zold-java-client/issues/61#issuecomment-479456124))

@g4s8 Job `gh:amihaiemil/zold-java-client#61` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#61](https://github.com/amihaiemil/zold-java-client/issues/61) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/f40abd01-d2c5-4d92-92c8-61b1b65187a4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@0crat wait for merging #62

**Comment by 0crat** [comment]
I'm not managing `amihaiemil/zold-java-client` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
The puzzle `56-5b6d6642` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#61](https://github.com/amihaiemil/zold-java-client/issues/61) is now out of scope
