### ISSUE TITLE
JsonResource.java: This is a todo which should a... 

### ISSUE THREAD

**Issue by charlesmike** [amihaiemil/zold-java-client#65]
The puzzle ``1-1036acea`` originating from #1 has to be resolved:

https://github.com/amihaiemil/zold-java-client/blob/657e842847fddf681ef991f8348cb0f6fa97444c/src/main/java/com/amihaiemil/zold/JsonResource.java#L40-L41

"This is a todo which should automatically be turned into an Issue by the PM, when it is pushed to master.".

It was created by @amihaiemil on 2020-11-30T12:23:28Z. Estimation is ``45 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-10T14:37:21.248549``.

Estimation here is ``45 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
