### ISSUE TITLE
Add User-Agent Inteceptor

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/zold-java-client#7]
Interceptor for the ``HttpClient`` to add the ``User-Agent`` HTTP header. See how it's done in [docker-java-api](https://github.com/amihaiemil/docker-java-api), including the ``config.properties`` file.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#7](https://github.com/amihaiemil/zold-java-client/issues/7) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/db6cd0b0-0288-4b7d-bbc7-36f8c08f788e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@ammartef45 don't forget about PDD. Always make a minimum PR -- for this ticket, for instance, I would make a PR with an interface and that ``config.properties`` file.

**Comment by ammaratef45** [comment]
@amihaiemil now should this issue be closed? if not what else should be done?

**Comment by amihaiemil** [comment]
@ammaratef45 right, I forgot, sorry :)

**Comment by 0crat** [comment]
Job was finished in 6 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#7](https://github.com/amihaiemil/zold-java-client/issues/7) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
